# -*- coding: utf-8 -*-
"""demo01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATD0aV6sk6Mi2Bd-RIvmS6tVfT7q9EF1
"""

# ============================================================
# 0. 필수 라이브러리 설치 (Colab 전용)
# ============================================================
!pip install mediapipe opencv-python matplotlib numpy pandas -q

# ============================================================
# 1. 라이브러리 임포트
# ============================================================
import cv2
import mediapipe as mp
import numpy as np
import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D  # 3D 활성화용 (사용 안 해도 필요)
from google.colab import files

mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles

# ============================================================
# 2. 이미지 업로드 (CCTV처럼 보이는 정적 이미지)
# ============================================================
print("CCTV 스타일 이미지 파일을 업로드하세요 (예: hallway.jpg)")
uploaded = files.upload()

# 업로드된 첫 번째 파일 이름 가져오기
image_path = list(uploaded.keys())[0]
print("사용할 이미지:", image_path)

# ============================================================
# 3. Pose Detection 함수 정의 (이미지 -> MediaPipe Pose)
#     이 부분이 Transfer Learning 모델 활용 지점
# ============================================================
def run_mediapipe_pose(image_path):
    # OpenCV로 이미지 로드 (BGR)
    image_bgr = cv2.imread(image_path)
    if image_bgr is None:
        raise FileNotFoundError(f"이미지를 찾을 수 없습니다: {image_path}")

    # 시각화를 위해 원본 복사
    image_bgr_copy = image_bgr.copy()

    # BGR -> RGB (MediaPipe는 RGB 사용)
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    #  Transfer Learning: 사전학습된 Pose 모델을 그대로 사용
    with mp_pose.Pose(
        static_image_mode=True,        # 정적 이미지이므로 True
        model_complexity=1,           # 0,1,2 중 1 정도면 충분
        enable_segmentation=False,
        min_detection_confidence=0.5  # 디텍션 신뢰도
    ) as pose:
        results = pose.process(image_rgb)

        # pose_landmarks (2D)와 pose_world_landmarks (3D) 모두 포함
        return image_bgr_copy, results

# ============================================================
# 4. 2D Pose 오버레이 (입력 이미지 위에 스켈레톤 그리기)
# ============================================================
def draw_2d_pose_overlay(image_bgr, results):
    if not results.pose_landmarks:
        print("[WARN] 포즈가 감지되지 않았습니다.")
        return image_bgr

    overlay = image_bgr.copy()

    # MediaPipe 기본 스타일로 랜드마크 + 연결선 그리기
    mp_drawing.draw_landmarks(
        overlay,
        results.pose_landmarks,
        mp_pose.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style()
    )
    return overlay

def show_bgr_image_in_colab(image_bgr, title="Image"):
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(6, 6))
    plt.imshow(image_rgb)
    plt.title(title)
    plt.axis('off')
    plt.show()

# ============================================================
# 5. 3D 스켈레톤을 그리기 위한 유틸 함수들
#    (MediaPipe world_landmarks → numpy 배열 → 3D plot)
# ============================================================
def extract_world_landmarks(results):
    """
    MediaPipe Pose 결과에서 3D world_landmarks를 추출하여
    (N, 3) numpy 배열과 visibility 리스트로 반환
    """
    if not results.pose_world_landmarks:
        print("[WARN] 3D world_landmarks가 없습니다.")
        return None, None

    landmarks = results.pose_world_landmarks.landmark
    xs, ys, zs, vs = [], [], [], []
    for lm in landmarks:
        xs.append(lm.x)
        ys.append(lm.y)
        zs.append(lm.z)
        vs.append(lm.visibility)

    points_3d = np.array([xs, ys, zs]).T  # (33, 3)
    visibility = np.array(vs)            # (33,)
    return points_3d, visibility


def get_pose_connections():
    """
    MediaPipe Pose 33개 랜드마크를 연결하는 스켈레톤 정의.
    (공식 connections를 써도 되지만, 여기서는 핵심 뼈대만 간단 정의)
    인덱스는 MediaPipe Pose 기준:
      11: 왼 어깨, 12: 오른 어깨, 13/14: 팔꿈치, 15/16: 손목,
      23/24: 골반, 25/26: 무릎, 27/28: 발목, 29/30, 31/32: 발
    """
    connections = [
        # 상체
        (11, 12),   # 어깨
        (11, 13), (13, 15),  # 왼팔
        (12, 14), (14, 16),  # 오른팔
        (11, 23), (12, 24),  # 몸통 옆 라인
        (23, 24),            # 골반

        # 왼쪽 다리
        (23, 25), (25, 27), (27, 29), (29, 31),

        # 오른쪽 다리
        (24, 26), (26, 28), (28, 30), (30, 32),
    ]
    return connections


def plot_3d_skeleton(points_3d, visibility=None, vis_thresh=0.5):
    """
    MediaPipe world 좌표 (x, y, z)를 사람이 서 있는 느낌으로 다시 배치:
      - X축 : 좌/우 (x 그대로)
      - Y축 : 깊이  (카메라에서 멀어지는 방향, z 그대로 사용하거나 -z로 바꿔도 OK)
      - Z축 : 위/아래 (-y 로 뒤집어서, 머리가 위로 가게)
    """
    if points_3d is None:
        print("[ERROR] 3D 포인트가 없습니다.")
        return

    # --- 좌표 변환 ---
    xs = points_3d[:, 0]        # 좌/우
    ys = points_3d[:, 2]        # 깊이 (원하면 -points_3d[:,2] 로 반대로)
    zs = -points_3d[:, 1]       # 위/아래 (y가 아래로 +니까 부호 반전)

    fig = plt.figure(figsize=(6, 6))
    ax = fig.add_subplot(111, projection='3d')

    # 전체 포인트 찍기
    ax.scatter(xs, ys, zs, s=20, alpha=0.6)

    connections = get_pose_connections()

    for i, j in connections:
        if i >= len(points_3d) or j >= len(points_3d):
            continue

        if visibility is not None:
            if visibility[i] < vis_thresh or visibility[j] < vis_thresh:
                continue

        x_line = [points_3d[i, 0], points_3d[j, 0]]
        y_line = [points_3d[i, 2], points_3d[j, 2]]
        z_line = [-points_3d[i, 1], -points_3d[j, 1]]
        ax.plot(x_line, y_line, z_line)

    ax.set_xlabel("X (left-right)")
    ax.set_ylabel("Y (depth)")
    ax.set_zlabel("Z (up-down)")

    # 축 비율 맞추기
    max_range = np.array([
        xs.max() - xs.min(),
        ys.max() - ys.min(),
        zs.max() - zs.min()
    ]).max()

    mid_x = (xs.max() + xs.min()) * 0.5
    mid_y = (ys.max() + ys.min()) * 0.5
    mid_z = (zs.max() + zs.min()) * 0.5

    ax.set_xlim(mid_x - max_range / 2, mid_x + max_range / 2)
    ax.set_ylim(mid_y - max_range / 2, mid_y + max_range / 2)
    ax.set_zlim(mid_z - max_range / 2, mid_z + max_range / 2)

    # 사람을 약간 대각선 위에서 보는 느낌
    ax.view_init(elev=20, azim=-60)
    plt.tight_layout()
    plt.show()

# ============================================================
# 6. 전체 파이프라인 실행:
#    이미지 -> MediaPipe Pose -> 2D 포즈 오버레이 -> 3D 스켈레톤
# ============================================================
# 1) Pose 추론
image_bgr, results = run_mediapipe_pose(image_path)

# 2) 2D 포즈 오버레이 이미지 표시
overlay_bgr = draw_2d_pose_overlay(image_bgr, results)
show_bgr_image_in_colab(image_bgr, title="Input Image")
show_bgr_image_in_colab(overlay_bgr, title="Pose Overlay (2D)")

# 3) 3D world_landmarks 추출
points_3d, visibility = extract_world_landmarks(results)

# 4) 3D 스켈레톤 시각화
plot_3d_skeleton(points_3d, visibility=visibility, vis_thresh=0.5)

import cv2
import numpy as np
import mediapipe as mp
import pandas as pd
import os
import argparse

mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=True, model_complexity=1, enable_segmentation=False)
mp_drawing = mp.solutions.drawing_utils
mp_style = mp.solutions.drawing_styles

def imread_rgb(path):
    """이미지를 RGB로 읽기"""
    bgr = cv2.imread(path)
    if bgr is None:
        raise FileNotFoundError(f"이미지를 읽을 수 없습니다: {path}")
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)

def mediapipe_infer(rgb):
    """MediaPipe Pose 추론"""
    res = pose.process(rgb)
    return res.pose_landmarks if res.pose_landmarks else None

def to_dataframe(landmarks, w, h):
    """정규화 좌표(x,y∈[0,1], z는 상대 깊이) DataFrame으로 변환"""
    data = []
    for i, lm in enumerate(landmarks.landmark):
        data.append({
            "id": i,
            "x": lm.x,
            "y": lm.y,
            "z": lm.z,
            "visibility": lm.visibility
        })
    df = pd.DataFrame(data)
    return df

def draw_pose(rgb, landmarks):
    """이미지 위에 포즈 오버레이"""
    annotated = rgb.copy()
    mp_drawing.draw_landmarks(
        annotated,
        landmarks,
        mp_pose.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_style.get_default_pose_landmarks_style())
    return annotated

def main(image_path, out_csv):
    os.makedirs(os.path.dirname(out_csv), exist_ok=True)

    rgb = imread_rgb(image_path)
    h, w = rgb.shape[:2]

    landmarks = mediapipe_infer(rgb)
    if landmarks is None:
        print("❌ 포즈를 인식하지 못했습니다. 다른 이미지로 시도하세요.")
        return

    df = to_dataframe(landmarks, w, h)
    df.to_csv(out_csv, index=False)
    print(f"✅ CSV 저장 완료: {out_csv}")
    print(df.head())

    # 시각화 이미지 저장 (선택)
    annotated = draw_pose(rgb, landmarks)
    preview_path = out_csv.replace("keypoints", "preview").replace(".csv", "_overlay.jpg")
    os.makedirs(os.path.dirname(preview_path), exist_ok=True)
    cv2.imwrite(preview_path, cv2.cvtColor(annotated, cv2.COLOR_RGB2BGR))
    print(f"🖼️ 포즈 시각화 이미지 저장: {preview_path}")

if __name__ == "__main__":
    # In Colab, we don't use argparse to get command line arguments.
    # We will directly call the main function with the image path from the previous step.
    # The image path is stored in the variable 'image_path' from the file upload cell (hzPFI_sfCzuy).
    # We'll also set a default output path for the CSV.

    # Ensure image_path exists from the previous cell execution
    if 'image_path' not in globals():
        raise FileNotFoundError("Image file path not found. Please run the file upload cell above.")

    output_csv_path = "data/keypoints/pose_sample.csv"
    main(image_path, output_csv_path)

!ls -R data

import pandas as pd
df = pd.read_csv("data/keypoints/pose_sample.csv")
df.head()